package com.detrening.detrening;

import android.content.Intent;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.view.View;
import android.widget.Button;
import android.widget.CheckBox;
import android.widget.ProgressBar;
import android.widget.TextView;
import android.widget.Toast;

import com.detrening.detrening.Authentication.Login;
import com.google.firebase.auth.FirebaseAuth;
import com.google.firebase.auth.FirebaseUser;
import com.google.firebase.database.DataSnapshot;
import com.google.firebase.database.DatabaseError;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;
import com.google.firebase.database.ValueEventListener;

public class Program extends AppCompatActivity {
    CheckBox c1, c2, c3, c4, c5, c6, c7, c8, c9, c10, c11, c12, c13, c14, c15;
    CheckBox c16, c17, c18, c19, c20, c21, c22, c23, c24, c25, c26, c27, c28, c29, c30;
    TextView emailUser;

    FirebaseAuth mFirebaseAuth;
    FirebaseUser mFirebaseUser;
    String emailCurrent;

    TextView progress;

    private FirebaseAuth firebaseAuth;
    private DatabaseReference databaseReference;

    public static final String Database_Path = "ProgressUser";

    public String userID;

    ProgressBar progressBar;

    Button btnReset;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_program);
        setTitle("Program");

        firebaseAuth = FirebaseAuth.getInstance();
        if (firebaseAuth.getCurrentUser() == null) {
            finish();
            startActivity(new Intent(this, Login.class));
        }

        btnReset = (Button) findViewById(R.id.btnResetProg);

        progressBar = (ProgressBar) findViewById(R.id.progressBarProg);

        FirebaseUser user = firebaseAuth.getCurrentUser();
        userID = user.getUid();


        databaseReference = FirebaseDatabase.getInstance().getReference(Database_Path);

        databaseReference.addValueEventListener(new ValueEventListener() {
            @Override
            public void onDataChange(DataSnapshot dataSnapshot) {
                String progressInf = dataSnapshot.child(userID).child("progress").getValue(String.class);

                if (progressInf == null) {
                    progress.setText("0%");
                    progressBar.setVisibility(View.INVISIBLE);
                    btnReset.setEnabled(false);
                    c1.setChecked(false);
                    c1.setClickable(true);
                    c2.setEnabled(false);
                    c3.setEnabled(false);
                    c4.setEnabled(false);
                    c5.setEnabled(false);
                    c6.setEnabled(false);
                    c7.setEnabled(false);
                    c8.setEnabled(false);
                    c9.setEnabled(false);
                    c10.setEnabled(false);
                    c11.setEnabled(false);
                    c12.setEnabled(false);
                    c13.setEnabled(false);
                    c14.setEnabled(false);
                    c15.setEnabled(false);
                    c16.setEnabled(false);
                    c17.setEnabled(false);
                    c18.setEnabled(false);
                    c19.setEnabled(false);
                    c20.setEnabled(false);
                    c21.setEnabled(false);
                    c22.setEnabled(false);
                    c23.setEnabled(false);
                    c24.setEnabled(false);
                    c25.setEnabled(false);
                    c26.setEnabled(false);
                    c27.setEnabled(false);
                    c28.setEnabled(false);
                    c29.setEnabled(false);
                    c30.setEnabled(false);

                } else if (progressInf.equals("0")) {
                    progress.setText("0%");
                    progressBar.setVisibility(View.INVISIBLE);
                    btnReset.setEnabled(false);
                    c1.setChecked(false);
                    c1.setClickable(true);
                    c2.setEnabled(false);
                    c3.setEnabled(false);
                    c4.setEnabled(false);
                    c5.setEnabled(false);
                    c6.setEnabled(false);
                    c7.setEnabled(false);
                    c8.setEnabled(false);
                    c9.setEnabled(false);
                    c10.setEnabled(false);
                    c11.setEnabled(false);
                    c12.setEnabled(false);
                    c13.setEnabled(false);
                    c14.setEnabled(false);
                    c15.setEnabled(false);
                    c16.setEnabled(false);
                    c17.setEnabled(false);
                    c18.setEnabled(false);
                    c19.setEnabled(false);
                    c20.setEnabled(false);
                    c21.setEnabled(false);
                    c22.setEnabled(false);
                    c23.setEnabled(false);
                    c24.setEnabled(false);
                    c25.setEnabled(false);
                    c26.setEnabled(false);
                    c27.setEnabled(false);
                    c28.setEnabled(false);
                    c29.setEnabled(false);
                    c30.setEnabled(false);

                } else if (progressInf.equals("3")) {
                    progress.setText(progressInf + "%");
                    progressBar.setVisibility(View.INVISIBLE);
                    c1.setChecked(true);
                    c1.setClickable(false);
                    c2.setClickable(true);
                    c3.setEnabled(false);
                    c4.setEnabled(false);
                    c5.setEnabled(false);
                    c6.setEnabled(false);
                    c7.setEnabled(false);
                    c8.setEnabled(false);
                    c9.setEnabled(false);
                    c10.setEnabled(false);
                    c11.setEnabled(false);
                    c12.setEnabled(false);
                    c13.setEnabled(false);
                    c14.setEnabled(false);
                    c15.setEnabled(false);
                    c16.setEnabled(false);
                    c17.setEnabled(false);
                    c18.setEnabled(false);
                    c19.setEnabled(false);
                    c20.setEnabled(false);
                    c21.setEnabled(false);
                    c22.setEnabled(false);
                    c23.setEnabled(false);
                    c24.setEnabled(false);
                    c25.setEnabled(false);
                    c26.setEnabled(false);
                    c27.setEnabled(false);
                    c28.setEnabled(false);
                    c29.setEnabled(false);
                    c30.setEnabled(false);

                } else if (progressInf.equals("6")) {
                    progress.setText(progressInf + "%");
                    progressBar.setVisibility(View.INVISIBLE);
                    c1.setChecked(true);
                    c2.setChecked(true);
                    c1.setClickable(false);
                    c2.setClickable(false);
                    c3.setClickable(true);
                    c4.setEnabled(false);
                    c5.setEnabled(false);
                    c6.setEnabled(false);
                    c7.setEnabled(false);
                    c8.setEnabled(false);
                    c9.setEnabled(false);
                    c10.setEnabled(false);
                    c11.setEnabled(false);
                    c12.setEnabled(false);
                    c13.setEnabled(false);
                    c14.setEnabled(false);
                    c15.setEnabled(false);
                    c16.setEnabled(false);
                    c17.setEnabled(false);
                    c18.setEnabled(false);
                    c19.setEnabled(false);
                    c20.setEnabled(false);
                    c21.setEnabled(false);
                    c22.setEnabled(false);
                    c23.setEnabled(false);
                    c24.setEnabled(false);
                    c25.setEnabled(false);
                    c26.setEnabled(false);
                    c27.setEnabled(false);
                    c28.setEnabled(false);
                    c29.setEnabled(false);
                    c30.setEnabled(false);
                } else if (progressInf.equals("9")) {
                    progress.setText(progressInf + "%");
                    progressBar.setVisibility(View.INVISIBLE);
                    c1.setChecked(true);
                    c2.setChecked(true);
                    c3.setChecked(true);
                    c1.setClickable(false);
                    c2.setClickable(false);
                    c3.setClickable(false);
                    c4.setClickable(true);
                    c5.setEnabled(false);
                    c6.setEnabled(false);
                    c7.setEnabled(false);
                    c8.setEnabled(false);
                    c9.setEnabled(false);
                    c10.setEnabled(false);
                    c11.setEnabled(false);
                    c12.setEnabled(false);
                    c13.setEnabled(false);
                    c14.setEnabled(false);
                    c15.setEnabled(false);
                    c16.setEnabled(false);
                    c17.setEnabled(false);
                    c18.setEnabled(false);
                    c19.setEnabled(false);
                    c20.setEnabled(false);
                    c21.setEnabled(false);
                    c22.setEnabled(false);
                    c23.setEnabled(false);
                    c24.setEnabled(false);
                    c25.setEnabled(false);
                    c26.setEnabled(false);
                    c27.setEnabled(false);
                    c28.setEnabled(false);
                    c29.setEnabled(false);
                    c30.setEnabled(false);
                } else if (progressInf.equals("12")) {
                    progress.setText(progressInf + "%");
                    progressBar.setVisibility(View.INVISIBLE);
                    c1.setChecked(true);
                    c2.setChecked(true);
                    c3.setChecked(true);
                    c4.setChecked(true);
                    c1.setClickable(false);
                    c2.setClickable(false);
                    c3.setClickable(false);
                    c4.setClickable(false);
                    c5.setClickable(true);
                    c6.setEnabled(false);
                    c7.setEnabled(false);
                    c8.setEnabled(false);
                    c9.setEnabled(false);
                    c10.setEnabled(false);
                    c11.setEnabled(false);
                    c12.setEnabled(false);
                    c13.setEnabled(false);
                    c14.setEnabled(false);
                    c15.setEnabled(false);
                    c16.setEnabled(false);
                    c17.setEnabled(false);
                    c18.setEnabled(false);
                    c19.setEnabled(false);
                    c20.setEnabled(false);
                    c21.setEnabled(false);
                    c22.setEnabled(false);
                    c23.setEnabled(false);
                    c24.setEnabled(false);
                    c25.setEnabled(false);
                    c26.setEnabled(false);
                    c27.setEnabled(false);
                    c28.setEnabled(false);
                    c29.setEnabled(false);
                    c30.setEnabled(false);
                } else if (progressInf.equals("15")) {
                    progress.setText(progressInf + "%");
                    progressBar.setVisibility(View.INVISIBLE);
                    c1.setChecked(true);
                    c2.setChecked(true);
                    c3.setChecked(true);
                    c4.setChecked(true);
                    c5.setChecked(true);
                    c1.setClickable(false);
                    c2.setClickable(false);
                    c3.setClickable(false);
                    c4.setClickable(false);
                    c5.setClickable(false);
                    c6.setClickable(true);
                    c7.setEnabled(false);
                    c8.setEnabled(false);
                    c9.setEnabled(false);
                    c10.setEnabled(false);
                    c11.setEnabled(false);
                    c12.setEnabled(false);
                    c13.setEnabled(false);
                    c14.setEnabled(false);
                    c15.setEnabled(false);
                    c16.setEnabled(false);
                    c17.setEnabled(false);
                    c18.setEnabled(false);
                    c19.setEnabled(false);
                    c20.setEnabled(false);
                    c21.setEnabled(false);
                    c22.setEnabled(false);
                    c23.setEnabled(false);
                    c24.setEnabled(false);
                    c25.setEnabled(false);
                    c26.setEnabled(false);
                    c27.setEnabled(false);
                    c28.setEnabled(false);
                    c29.setEnabled(false);
                    c30.setEnabled(false);
                } else if (progressInf.equals("18")) {
                    progress.setText(progressInf + "%");
                    progressBar.setVisibility(View.INVISIBLE);
                    c1.setChecked(true);
                    c2.setChecked(true);
                    c3.setChecked(true);
                    c4.setChecked(true);
                    c5.setChecked(true);
                    c6.setChecked(true);
                    c1.setClickable(false);
                    c2.setClickable(false);
                    c3.setClickable(false);
                    c4.setClickable(false);
                    c5.setClickable(false);
                    c6.setClickable(false);
                    c7.setClickable(true);
                    c8.setEnabled(false);
                    c9.setEnabled(false);
                    c10.setEnabled(false);
                    c11.setEnabled(false);
                    c12.setEnabled(false);
                    c13.setEnabled(false);
                    c14.setEnabled(false);
                    c15.setEnabled(false);
                    c16.setEnabled(false);
                    c17.setEnabled(false);
                    c18.setEnabled(false);
                    c19.setEnabled(false);
                    c20.setEnabled(false);
                    c21.setEnabled(false);
                    c22.setEnabled(false);
                    c23.setEnabled(false);
                    c24.setEnabled(false);
                    c25.setEnabled(false);
                    c26.setEnabled(false);
                    c27.setEnabled(false);
                    c28.setEnabled(false);
                    c29.setEnabled(false);
                    c30.setEnabled(false);
                } else if (progressInf.equals("21")) {
                    progress.setText(progressInf + "%");
                    progressBar.setVisibility(View.INVISIBLE);
                    c1.setChecked(true);
                    c2.setChecked(true);
                    c3.setChecked(true);
                    c4.setChecked(true);
                    c5.setChecked(true);
                    c6.setChecked(true);
                    c7.setChecked(true);
                    c1.setClickable(false);
                    c2.setClickable(false);
                    c3.setClickable(false);
                    c4.setClickable(false);
                    c5.setClickable(false);
                    c6.setClickable(false);
                    c7.setClickable(false);
                    c8.setClickable(true);
                    c9.setEnabled(false);
                    c10.setEnabled(false);
                    c11.setEnabled(false);
                    c12.setEnabled(false);
                    c13.setEnabled(false);
                    c14.setEnabled(false);
                    c15.setEnabled(false);
                    c16.setEnabled(false);
                    c17.setEnabled(false);
                    c18.setEnabled(false);
                    c19.setEnabled(false);
                    c20.setEnabled(false);
                    c21.setEnabled(false);
                    c22.setEnabled(false);
                    c23.setEnabled(false);
                    c24.setEnabled(false);
                    c25.setEnabled(false);
                    c26.setEnabled(false);
                    c27.setEnabled(false);
                    c28.setEnabled(false);
                    c29.setEnabled(false);
                    c30.setEnabled(false);
                } else if (progressInf.equals("24")) {
                    progress.setText(progressInf + "%");
                    progressBar.setVisibility(View.INVISIBLE);
                    c1.setChecked(true);
                    c2.setChecked(true);
                    c3.setChecked(true);
                    c4.setChecked(true);
                    c5.setChecked(true);
                    c6.setChecked(true);
                    c7.setChecked(true);
                    c8.setChecked(true);
                    c1.setClickable(false);
                    c2.setClickable(false);
                    c3.setClickable(false);
                    c4.setClickable(false);
                    c5.setClickable(false);
                    c6.setClickable(false);
                    c7.setClickable(false);
                    c8.setClickable(false);
                    c9.setClickable(true);
                    c10.setEnabled(false);
                    c11.setEnabled(false);
                    c12.setEnabled(false);
                    c13.setEnabled(false);
                    c14.setEnabled(false);
                    c15.setEnabled(false);
                    c16.setEnabled(false);
                    c17.setEnabled(false);
                    c18.setEnabled(false);
                    c19.setEnabled(false);
                    c20.setEnabled(false);
                    c21.setEnabled(false);
                    c22.setEnabled(false);
                    c23.setEnabled(false);
                    c24.setEnabled(false);
                    c25.setEnabled(false);
                    c26.setEnabled(false);
                    c27.setEnabled(false);
                    c28.setEnabled(false);
                    c29.setEnabled(false);
                    c30.setEnabled(false);
                } else if (progressInf.equals("27")) {
                    progress.setText(progressInf + "%");
                    progressBar.setVisibility(View.INVISIBLE);
                    c1.setChecked(true);
                    c2.setChecked(true);
                    c3.setChecked(true);
                    c4.setChecked(true);
                    c5.setChecked(true);
                    c6.setChecked(true);
                    c7.setChecked(true);
                    c8.setChecked(true);
                    c9.setChecked(true);
                    c1.setClickable(false);
                    c2.setClickable(false);
                    c3.setClickable(false);
                    c4.setClickable(false);
                    c5.setClickable(false);
                    c6.setClickable(false);
                    c7.setClickable(false);
                    c8.setClickable(false);
                    c9.setClickable(false);
                    c10.setClickable(true);
                    c11.setEnabled(false);
                    c12.setEnabled(false);
                    c13.setEnabled(false);
                    c14.setEnabled(false);
                    c15.setEnabled(false);
                    c16.setEnabled(false);
                    c17.setEnabled(false);
                    c18.setEnabled(false);
                    c19.setEnabled(false);
                    c20.setEnabled(false);
                    c21.setEnabled(false);
                    c22.setEnabled(false);
                    c23.setEnabled(false);
                    c24.setEnabled(false);
                    c25.setEnabled(false);
                    c26.setEnabled(false);
                    c27.setEnabled(false);
                    c28.setEnabled(false);
                    c29.setEnabled(false);
                    c30.setEnabled(false);
                } else if (progressInf.equals("30")) {
                    progress.setText(progressInf + "%");
                    progressBar.setVisibility(View.INVISIBLE);
                    c1.setChecked(true);
                    c2.setChecked(true);
                    c3.setChecked(true);
                    c4.setChecked(true);
                    c5.setChecked(true);
                    c6.setChecked(true);
                    c7.setChecked(true);
                    c8.setChecked(true);
                    c9.setChecked(true);
                    c10.setChecked(true);
                    c1.setClickable(false);
                    c2.setClickable(false);
                    c3.setClickable(false);
                    c4.setClickable(false);
                    c5.setClickable(false);
                    c6.setClickable(false);
                    c7.setClickable(false);
                    c8.setClickable(false);
                    c9.setClickable(false);
                    c10.setClickable(false);
                    c11.setClickable(true);
                    c12.setEnabled(false);
                    c13.setEnabled(false);
                    c14.setEnabled(false);
                    c15.setEnabled(false);
                    c16.setEnabled(false);
                    c17.setEnabled(false);
                    c18.setEnabled(false);
                    c19.setEnabled(false);
                    c20.setEnabled(false);
                    c21.setEnabled(false);
                    c22.setEnabled(false);
                    c23.setEnabled(false);
                    c24.setEnabled(false);
                    c25.setEnabled(false);
                    c26.setEnabled(false);
                    c27.setEnabled(false);
                    c28.setEnabled(false);
                    c29.setEnabled(false);
                    c30.setEnabled(false);
                } else if (progressInf.equals("33")) {
                    progress.setText(progressInf + "%");
                    progressBar.setVisibility(View.INVISIBLE);
                    c1.setChecked(true);
                    c2.setChecked(true);
                    c3.setChecked(true);
                    c4.setChecked(true);
                    c5.setChecked(true);
                    c6.setChecked(true);
                    c7.setChecked(true);
                    c8.setChecked(true);
                    c9.setChecked(true);
                    c10.setChecked(true);
                    c11.setChecked(true);
                    c1.setClickable(false);
                    c2.setClickable(false);
                    c3.setClickable(false);
                    c4.setClickable(false);
                    c5.setClickable(false);
                    c6.setClickable(false);
                    c7.setClickable(false);
                    c8.setClickable(false);
                    c9.setClickable(false);
                    c10.setClickable(false);
                    c11.setClickable(false);
                    c12.setClickable(true);
                    c13.setEnabled(false);
                    c14.setEnabled(false);
                    c15.setEnabled(false);
                    c16.setEnabled(false);
                    c17.setEnabled(false);
                    c18.setEnabled(false);
                    c19.setEnabled(false);
                    c20.setEnabled(false);
                    c21.setEnabled(false);
                    c22.setEnabled(false);
                    c23.setEnabled(false);
                    c24.setEnabled(false);
                    c25.setEnabled(false);
                    c26.setEnabled(false);
                    c27.setEnabled(false);
                    c28.setEnabled(false);
                    c29.setEnabled(false);
                    c30.setEnabled(false);
                } else if (progressInf.equals("36")) {
                    progress.setText(progressInf + "%");
                    progressBar.setVisibility(View.INVISIBLE);
                    c1.setChecked(true);
                    c2.setChecked(true);
                    c3.setChecked(true);
                    c4.setChecked(true);
                    c5.setChecked(true);
                    c6.setChecked(true);
                    c7.setChecked(true);
                    c8.setChecked(true);
                    c9.setChecked(true);
                    c10.setChecked(true);
                    c11.setChecked(true);
                    c12.setChecked(true);
                    c1.setClickable(false);
                    c2.setClickable(false);
                    c3.setClickable(false);
                    c4.setClickable(false);
                    c5.setClickable(false);
                    c6.setClickable(false);
                    c7.setClickable(false);
                    c8.setClickable(false);
                    c9.setClickable(false);
                    c10.setClickable(false);
                    c11.setClickable(false);
                    c12.setClickable(false);
                    c13.setClickable(true);
                    c14.setEnabled(false);
                    c15.setEnabled(false);
                    c16.setEnabled(false);
                    c17.setEnabled(false);
                    c18.setEnabled(false);
                    c19.setEnabled(false);
                    c20.setEnabled(false);
                    c21.setEnabled(false);
                    c22.setEnabled(false);
                    c23.setEnabled(false);
                    c24.setEnabled(false);
                    c25.setEnabled(false);
                    c26.setEnabled(false);
                    c27.setEnabled(false);
                    c28.setEnabled(false);
                    c29.setEnabled(false);
                    c30.setEnabled(false);
                } else if (progressInf.equals("39")) {
                    progress.setText(progressInf + "%");
                    progressBar.setVisibility(View.INVISIBLE);
                    c1.setChecked(true);
                    c2.setChecked(true);
                    c3.setChecked(true);
                    c4.setChecked(true);
                    c5.setChecked(true);
                    c6.setChecked(true);
                    c7.setChecked(true);
                    c8.setChecked(true);
                    c9.setChecked(true);
                    c10.setChecked(true);
                    c11.setChecked(true);
                    c12.setChecked(true);
                    c13.setChecked(true);
                    c1.setClickable(false);
                    c2.setClickable(false);
                    c3.setClickable(false);
                    c4.setClickable(false);
                    c5.setClickable(false);
                    c6.setClickable(false);
                    c7.setClickable(false);
                    c8.setClickable(false);
                    c9.setClickable(false);
                    c10.setClickable(false);
                    c11.setClickable(false);
                    c12.setClickable(false);
                    c13.setClickable(false);
                    c14.setClickable(true);
                    c15.setEnabled(false);
                    c16.setEnabled(false);
                    c17.setEnabled(false);
                    c18.setEnabled(false);
                    c19.setEnabled(false);
                    c20.setEnabled(false);
                    c21.setEnabled(false);
                    c22.setEnabled(false);
                    c23.setEnabled(false);
                    c24.setEnabled(false);
                    c25.setEnabled(false);
                    c26.setEnabled(false);
                    c27.setEnabled(false);
                    c28.setEnabled(false);
                    c29.setEnabled(false);
                    c30.setEnabled(false);
                } else if (progressInf.equals("42")) {
                    progress.setText(progressInf + "%");
                    progressBar.setVisibility(View.INVISIBLE);
                    c1.setChecked(true);
                    c2.setChecked(true);
                    c3.setChecked(true);
                    c4.setChecked(true);
                    c5.setChecked(true);
                    c6.setChecked(true);
                    c7.setChecked(true);
                    c8.setChecked(true);
                    c9.setChecked(true);
                    c10.setChecked(true);
                    c11.setChecked(true);
                    c12.setChecked(true);
                    c13.setChecked(true);
                    c14.setChecked(true);
                    c1.setClickable(false);
                    c2.setClickable(false);
                    c3.setClickable(false);
                    c4.setClickable(false);
                    c5.setClickable(false);
                    c6.setClickable(false);
                    c7.setClickable(false);
                    c8.setClickable(false);
                    c9.setClickable(false);
                    c10.setClickable(false);
                    c11.setClickable(false);
                    c12.setClickable(false);
                    c13.setClickable(false);
                    c14.setClickable(false);
                    c15.setClickable(true);
                    c16.setEnabled(false);
                    c17.setEnabled(false);
                    c18.setEnabled(false);
                    c19.setEnabled(false);
                    c20.setEnabled(false);
                    c21.setEnabled(false);
                    c22.setEnabled(false);
                    c23.setEnabled(false);
                    c24.setEnabled(false);
                    c25.setEnabled(false);
                    c26.setEnabled(false);
                    c27.setEnabled(false);
                    c28.setEnabled(false);
                    c29.setEnabled(false);
                    c30.setEnabled(false);
                } else if (progressInf.equals("45")) {
                    progress.setText(progressInf + "%");
                    progressBar.setVisibility(View.INVISIBLE);
                    c1.setChecked(true);
                    c2.setChecked(true);
                    c3.setChecked(true);
                    c4.setChecked(true);
                    c5.setChecked(true);
                    c6.setChecked(true);
                    c7.setChecked(true);
                    c8.setChecked(true);
                    c9.setChecked(true);
                    c10.setChecked(true);
                    c11.setChecked(true);
                    c12.setChecked(true);
                    c13.setChecked(true);
                    c14.setChecked(true);
                    c15.setChecked(true);
                    c1.setClickable(false);
                    c2.setClickable(false);
                    c3.setClickable(false);
                    c4.setClickable(false);
                    c5.setClickable(false);
                    c6.setClickable(false);
                    c7.setClickable(false);
                    c8.setClickable(false);
                    c9.setClickable(false);
                    c10.setClickable(false);
                    c11.setClickable(false);
                    c12.setClickable(false);
                    c13.setClickable(false);
                    c14.setClickable(false);
                    c15.setClickable(false);
                    c16.setClickable(true);
                    c17.setEnabled(false);
                    c18.setEnabled(false);
                    c19.setEnabled(false);
                    c20.setEnabled(false);
                    c21.setEnabled(false);
                    c22.setEnabled(false);
                    c23.setEnabled(false);
                    c24.setEnabled(false);
                    c25.setEnabled(false);
                    c26.setEnabled(false);
                    c27.setEnabled(false);
                    c28.setEnabled(false);
                    c29.setEnabled(false);
                    c30.setEnabled(false);
                } else if (progressInf.equals("48")) {
                    progress.setText(progressInf + "%");
                    progressBar.setVisibility(View.INVISIBLE);
                    c1.setChecked(true);
                    c2.setChecked(true);
                    c3.setChecked(true);
                    c4.setChecked(true);
                    c5.setChecked(true);
                    c6.setChecked(true);
                    c7.setChecked(true);
                    c8.setChecked(true);
                    c9.setChecked(true);
                    c10.setChecked(true);
                    c11.setChecked(true);
                    c12.setChecked(true);
                    c13.setChecked(true);
                    c14.setChecked(true);
                    c15.setChecked(true);
                    c16.setChecked(true);
                    c1.setClickable(false);
                    c2.setClickable(false);
                    c3.setClickable(false);
                    c4.setClickable(false);
                    c5.setClickable(false);
                    c6.setClickable(false);
                    c7.setClickable(false);
                    c8.setClickable(false);
                    c9.setClickable(false);
                    c10.setClickable(false);
                    c11.setClickable(false);
                    c12.setClickable(false);
                    c13.setClickable(false);
                    c14.setClickable(false);
                    c15.setClickable(false);
                    c16.setClickable(false);
                    c17.setClickable(true);
                    c18.setEnabled(false);
                    c19.setEnabled(false);
                    c20.setEnabled(false);
                    c21.setEnabled(false);
                    c22.setEnabled(false);
                    c23.setEnabled(false);
                    c24.setEnabled(false);
                    c25.setEnabled(false);
                    c26.setEnabled(false);
                    c27.setEnabled(false);
                    c28.setEnabled(false);
                    c29.setEnabled(false);
                    c30.setEnabled(false);
                } else if (progressInf.equals("51")) {
                    progress.setText(progressInf + "%");
                    progressBar.setVisibility(View.INVISIBLE);
                    c1.setChecked(true);
                    c2.setChecked(true);
                    c3.setChecked(true);
                    c4.setChecked(true);
                    c5.setChecked(true);
                    c6.setChecked(true);
                    c7.setChecked(true);
                    c8.setChecked(true);
                    c9.setChecked(true);
                    c10.setChecked(true);
                    c11.setChecked(true);
                    c12.setChecked(true);
                    c13.setChecked(true);
                    c14.setChecked(true);
                    c15.setChecked(true);
                    c16.setChecked(true);
                    c17.setChecked(true);
                    c1.setClickable(false);
                    c2.setClickable(false);
                    c3.setClickable(false);
                    c4.setClickable(false);
                    c5.setClickable(false);
                    c6.setClickable(false);
                    c7.setClickable(false);
                    c8.setClickable(false);
                    c9.setClickable(false);
                    c10.setClickable(false);
                    c11.setClickable(false);
                    c12.setClickable(false);
                    c13.setClickable(false);
                    c14.setClickable(false);
                    c15.setClickable(false);
                    c16.setClickable(false);
                    c17.setClickable(false);
                    c18.setClickable(true);
                    c19.setEnabled(false);
                    c20.setEnabled(false);
                    c21.setEnabled(false);
                    c22.setEnabled(false);
                    c23.setEnabled(false);
                    c24.setEnabled(false);
                    c25.setEnabled(false);
                    c26.setEnabled(false);
                    c27.setEnabled(false);
                    c28.setEnabled(false);
                    c29.setEnabled(false);
                    c30.setEnabled(false);
                } else if (progressInf.equals("54")) {
                    progress.setText(progressInf + "%");
                    progressBar.setVisibility(View.INVISIBLE);
                    c1.setChecked(true);
                    c2.setChecked(true);
                    c3.setChecked(true);
                    c4.setChecked(true);
                    c5.setChecked(true);
                    c6.setChecked(true);
                    c7.setChecked(true);
                    c8.setChecked(true);
                    c9.setChecked(true);
                    c10.setChecked(true);
                    c11.setChecked(true);
                    c12.setChecked(true);
                    c13.setChecked(true);
                    c14.setChecked(true);
                    c15.setChecked(true);
                    c16.setChecked(true);
                    c17.setChecked(true);
                    c18.setChecked(true);
                    c1.setClickable(false);
                    c2.setClickable(false);
                    c3.setClickable(false);
                    c4.setClickable(false);
                    c5.setClickable(false);
                    c6.setClickable(false);
                    c7.setClickable(false);
                    c8.setClickable(false);
                    c9.setClickable(false);
                    c10.setClickable(false);
                    c11.setClickable(false);
                    c12.setClickable(false);
                    c13.setClickable(false);
                    c14.setClickable(false);
                    c15.setClickable(false);
                    c16.setClickable(false);
                    c17.setClickable(false);
                    c18.setClickable(false);
                    c19.setClickable(true);
                    c20.setEnabled(false);
                    c21.setEnabled(false);
                    c22.setEnabled(false);
                    c23.setEnabled(false);
                    c24.setEnabled(false);
                    c25.setEnabled(false);
                    c26.setEnabled(false);
                    c27.setEnabled(false);
                    c28.setEnabled(false);
                    c29.setEnabled(false);
                    c30.setEnabled(false);
                } else if (progressInf.equals("57")) {
                    progress.setText(progressInf + "%");
                    progressBar.setVisibility(View.INVISIBLE);
                    c1.setChecked(true);
                    c2.setChecked(true);
                    c3.setChecked(true);
                    c4.setChecked(true);
                    c5.setChecked(true);
                    c6.setChecked(true);
                    c7.setChecked(true);
                    c8.setChecked(true);
                    c9.setChecked(true);
                    c10.setChecked(true);
                    c11.setChecked(true);
                    c12.setChecked(true);
                    c13.setChecked(true);
                    c14.setChecked(true);
                    c15.setChecked(true);
                    c16.setChecked(true);
                    c17.setChecked(true);
                    c18.setChecked(true);
                    c19.setChecked(true);
                    c1.setClickable(false);
                    c2.setClickable(false);
                    c3.setClickable(false);
                    c4.setClickable(false);
                    c5.setClickable(false);
                    c6.setClickable(false);
                    c7.setClickable(false);
                    c8.setClickable(false);
                    c9.setClickable(false);
                    c10.setClickable(false);
                    c11.setClickable(false);
                    c12.setClickable(false);
                    c13.setClickable(false);
                    c14.setClickable(false);
                    c15.setClickable(false);
                    c16.setClickable(false);
                    c17.setClickable(false);
                    c18.setClickable(false);
                    c19.setClickable(false);
                    c20.setClickable(true);
                    c21.setEnabled(false);
                    c22.setEnabled(false);
                    c23.setEnabled(false);
                    c24.setEnabled(false);
                    c25.setEnabled(false);
                    c26.setEnabled(false);
                    c27.setEnabled(false);
                    c28.setEnabled(false);
                    c29.setEnabled(false);
                    c30.setEnabled(false);
                } else if (progressInf.equals("60")) {
                    progress.setText(progressInf + "%");
                    progressBar.setVisibility(View.INVISIBLE);
                    c1.setChecked(true);
                    c2.setChecked(true);
                    c3.setChecked(true);
                    c4.setChecked(true);
                    c5.setChecked(true);
                    c6.setChecked(true);
                    c7.setChecked(true);
                    c8.setChecked(true);
                    c9.setChecked(true);
                    c10.setChecked(true);
                    c11.setChecked(true);
                    c12.setChecked(true);
                    c13.setChecked(true);
                    c14.setChecked(true);
                    c15.setChecked(true);
                    c16.setChecked(true);
                    c17.setChecked(true);
                    c18.setChecked(true);
                    c19.setChecked(true);
                    c20.setChecked(true);
                    c1.setClickable(false);
                    c2.setClickable(false);
                    c3.setClickable(false);
                    c4.setClickable(false);
                    c5.setClickable(false);
                    c6.setClickable(false);
                    c7.setClickable(false);
                    c8.setClickable(false);
                    c9.setClickable(false);
                    c10.setClickable(false);
                    c11.setClickable(false);
                    c12.setClickable(false);
                    c13.setClickable(false);
                    c14.setClickable(false);
                    c15.setClickable(false);
                    c16.setClickable(false);
                    c17.setClickable(false);
                    c18.setClickable(false);
                    c19.setClickable(false);
                    c20.setClickable(false);
                    c21.setClickable(true);
                    c22.setEnabled(false);
                    c23.setEnabled(false);
                    c24.setEnabled(false);
                    c25.setEnabled(false);
                    c26.setEnabled(false);
                    c27.setEnabled(false);
                    c28.setEnabled(false);
                    c29.setEnabled(false);
                    c30.setEnabled(false);
                } else if (progressInf.equals("63")) {
                    progress.setText(progressInf + "%");
                    progressBar.setVisibility(View.INVISIBLE);
                    c1.setChecked(true);
                    c2.setChecked(true);
                    c3.setChecked(true);
                    c4.setChecked(true);
                    c5.setChecked(true);
                    c6.setChecked(true);
                    c7.setChecked(true);
                    c8.setChecked(true);
                    c9.setChecked(true);
                    c10.setChecked(true);
                    c11.setChecked(true);
                    c12.setChecked(true);
                    c13.setChecked(true);
                    c14.setChecked(true);
                    c15.setChecked(true);
                    c16.setChecked(true);
                    c17.setChecked(true);
                    c18.setChecked(true);
                    c19.setChecked(true);
                    c20.setChecked(true);
                    c21.setChecked(true);
                    c1.setClickable(false);
                    c2.setClickable(false);
                    c3.setClickable(false);
                    c4.setClickable(false);
                    c5.setClickable(false);
                    c6.setClickable(false);
                    c7.setClickable(false);
                    c8.setClickable(false);
                    c9.setClickable(false);
                    c10.setClickable(false);
                    c11.setClickable(false);
                    c12.setClickable(false);
                    c13.setClickable(false);
                    c14.setClickable(false);
                    c15.setClickable(false);
                    c16.setClickable(false);
                    c17.setClickable(false);
                    c18.setClickable(false);
                    c19.setClickable(false);
                    c20.setClickable(false);
                    c21.setClickable(false);
                    c22.setClickable(true);
                    c23.setEnabled(false);
                    c24.setEnabled(false);
                    c25.setEnabled(false);
                    c26.setEnabled(false);
                    c27.setEnabled(false);
                    c28.setEnabled(false);
                    c29.setEnabled(false);
                    c30.setEnabled(false);
                } else if (progressInf.equals("66")) {
                    progress.setText(progressInf + "%");
                    progressBar.setVisibility(View.INVISIBLE);
                    c1.setChecked(true);
                    c2.setChecked(true);
                    c3.setChecked(true);
                    c4.setChecked(true);
                    c5.setChecked(true);
                    c6.setChecked(true);
                    c7.setChecked(true);
                    c8.setChecked(true);
                    c9.setChecked(true);
                    c10.setChecked(true);
                    c11.setChecked(true);
                    c12.setChecked(true);
                    c13.setChecked(true);
                    c14.setChecked(true);
                    c15.setChecked(true);
                    c16.setChecked(true);
                    c17.setChecked(true);
                    c18.setChecked(true);
                    c19.setChecked(true);
                    c20.setChecked(true);
                    c21.setChecked(true);
                    c22.setChecked(true);
                    c1.setClickable(false);
                    c2.setClickable(false);
                    c3.setClickable(false);
                    c4.setClickable(false);
                    c5.setClickable(false);
                    c6.setClickable(false);
                    c7.setClickable(false);
                    c8.setClickable(false);
                    c9.setClickable(false);
                    c10.setClickable(false);
                    c11.setClickable(false);
                    c12.setClickable(false);
                    c13.setClickable(false);
                    c14.setClickable(false);
                    c15.setClickable(false);
                    c16.setClickable(false);
                    c17.setClickable(false);
                    c18.setClickable(false);
                    c19.setClickable(false);
                    c20.setClickable(false);
                    c21.setClickable(false);
                    c22.setClickable(false);
                    c23.setClickable(true);
                    c24.setEnabled(false);
                    c25.setEnabled(false);
                    c26.setEnabled(false);
                    c27.setEnabled(false);
                    c28.setEnabled(false);
                    c29.setEnabled(false);
                    c30.setEnabled(false);
                } else if (progressInf.equals("69")) {
                    progress.setText(progressInf + "%");
                    progressBar.setVisibility(View.INVISIBLE);
                    c1.setChecked(true);
                    c2.setChecked(true);
                    c3.setChecked(true);
                    c4.setChecked(true);
                    c5.setChecked(true);
                    c6.setChecked(true);
                    c7.setChecked(true);
                    c8.setChecked(true);
                    c9.setChecked(true);
                    c10.setChecked(true);
                    c11.setChecked(true);
                    c12.setChecked(true);
                    c13.setChecked(true);
                    c14.setChecked(true);
                    c15.setChecked(true);
                    c16.setChecked(true);
                    c17.setChecked(true);
                    c18.setChecked(true);
                    c19.setChecked(true);
                    c20.setChecked(true);
                    c21.setChecked(true);
                    c22.setChecked(true);
                    c23.setChecked(true);
                    c1.setClickable(false);
                    c2.setClickable(false);
                    c3.setClickable(false);
                    c4.setClickable(false);
                    c5.setClickable(false);
                    c6.setClickable(false);
                    c7.setClickable(false);
                    c8.setClickable(false);
                    c9.setClickable(false);
                    c10.setClickable(false);
                    c11.setClickable(false);
                    c12.setClickable(false);
                    c13.setClickable(false);
                    c14.setClickable(false);
                    c15.setClickable(false);
                    c16.setClickable(false);
                    c17.setClickable(false);
                    c18.setClickable(false);
                    c19.setClickable(false);
                    c20.setClickable(false);
                    c21.setClickable(false);
                    c22.setClickable(false);
                    c23.setClickable(false);
                    c24.setClickable(true);
                    c25.setEnabled(false);
                    c26.setEnabled(false);
                    c27.setEnabled(false);
                    c28.setEnabled(false);
                    c29.setEnabled(false);
                    c30.setEnabled(false);
                } else if (progressInf.equals("72")) {
                    progress.setText(progressInf + "%");
                    progressBar.setVisibility(View.INVISIBLE);
                    c1.setChecked(true);
                    c2.setChecked(true);
                    c3.setChecked(true);
                    c4.setChecked(true);
                    c5.setChecked(true);
                    c6.setChecked(true);
                    c7.setChecked(true);
                    c8.setChecked(true);
                    c9.setChecked(true);
                    c10.setChecked(true);
                    c11.setChecked(true);
                    c12.setChecked(true);
                    c13.setChecked(true);
                    c14.setChecked(true);
                    c15.setChecked(true);
                    c16.setChecked(true);
                    c17.setChecked(true);
                    c18.setChecked(true);
                    c19.setChecked(true);
                    c20.setChecked(true);
                    c21.setChecked(true);
                    c22.setChecked(true);
                    c23.setChecked(true);
                    c24.setChecked(true);
                    c1.setClickable(false);
                    c2.setClickable(false);
                    c3.setClickable(false);
                    c4.setClickable(false);
                    c5.setClickable(false);
                    c6.setClickable(false);
                    c7.setClickable(false);
                    c8.setClickable(false);
                    c9.setClickable(false);
                    c10.setClickable(false);
                    c11.setClickable(false);
                    c12.setClickable(false);
                    c13.setClickable(false);
                    c14.setClickable(false);
                    c15.setClickable(false);
                    c16.setClickable(false);
                    c17.setClickable(false);
                    c18.setClickable(false);
                    c19.setClickable(false);
                    c20.setClickable(false);
                    c21.setClickable(false);
                    c22.setClickable(false);
                    c23.setClickable(false);
                    c24.setClickable(false);
                    c25.setClickable(true);
                    c26.setEnabled(false);
                    c27.setEnabled(false);
                    c28.setEnabled(false);
                    c29.setEnabled(false);
                    c30.setEnabled(false);
                } else if (progressInf.equals("75")) {
                    progress.setText(progressInf + "%");
                    progressBar.setVisibility(View.INVISIBLE);
                    c1.setChecked(true);
                    c2.setChecked(true);
                    c3.setChecked(true);
                    c4.setChecked(true);
                    c5.setChecked(true);
                    c6.setChecked(true);
                    c7.setChecked(true);
                    c8.setChecked(true);
                    c9.setChecked(true);
                    c10.setChecked(true);
                    c11.setChecked(true);
                    c12.setChecked(true);
                    c13.setChecked(true);
                    c14.setChecked(true);
                    c15.setChecked(true);
                    c16.setChecked(true);
                    c17.setChecked(true);
                    c18.setChecked(true);
                    c19.setChecked(true);
                    c20.setChecked(true);
                    c21.setChecked(true);
                    c22.setChecked(true);
                    c23.setChecked(true);
                    c24.setChecked(true);
                    c25.setChecked(true);
                    c1.setClickable(false);
                    c2.setClickable(false);
                    c3.setClickable(false);
                    c4.setClickable(false);
                    c5.setClickable(false);
                    c6.setClickable(false);
                    c7.setClickable(false);
                    c8.setClickable(false);
                    c9.setClickable(false);
                    c10.setClickable(false);
                    c11.setClickable(false);
                    c12.setClickable(false);
                    c13.setClickable(false);
                    c14.setClickable(false);
                    c15.setClickable(false);
                    c16.setClickable(false);
                    c17.setClickable(false);
                    c18.setClickable(false);
                    c19.setClickable(false);
                    c20.setClickable(false);
                    c21.setClickable(false);
                    c22.setClickable(false);
                    c23.setClickable(false);
                    c24.setClickable(false);
                    c25.setClickable(false);
                    c26.setClickable(true);
                    c27.setEnabled(false);
                    c28.setEnabled(false);
                    c29.setEnabled(false);
                    c30.setEnabled(false);
                } else if (progressInf.equals("79")) {
                    progress.setText(progressInf + "%");
                    progressBar.setVisibility(View.INVISIBLE);
                    c1.setChecked(true);
                    c2.setChecked(true);
                    c3.setChecked(true);
                    c4.setChecked(true);
                    c5.setChecked(true);
                    c6.setChecked(true);
                    c7.setChecked(true);
                    c8.setChecked(true);
                    c9.setChecked(true);
                    c10.setChecked(true);
                    c11.setChecked(true);
                    c12.setChecked(true);
                    c13.setChecked(true);
                    c14.setChecked(true);
                    c15.setChecked(true);
                    c16.setChecked(true);
                    c17.setChecked(true);
                    c18.setChecked(true);
                    c19.setChecked(true);
                    c20.setChecked(true);
                    c21.setChecked(true);
                    c22.setChecked(true);
                    c23.setChecked(true);
                    c24.setChecked(true);
                    c25.setChecked(true);
                    c26.setChecked(true);
                    c1.setClickable(false);
                    c2.setClickable(false);
                    c3.setClickable(false);
                    c4.setClickable(false);
                    c5.setClickable(false);
                    c6.setClickable(false);
                    c7.setClickable(false);
                    c8.setClickable(false);
                    c9.setClickable(false);
                    c10.setClickable(false);
                    c11.setClickable(false);
                    c12.setClickable(false);
                    c13.setClickable(false);
                    c14.setClickable(false);
                    c15.setClickable(false);
                    c16.setClickable(false);
                    c17.setClickable(false);
                    c18.setClickable(false);
                    c19.setClickable(false);
                    c20.setClickable(false);
                    c21.setClickable(false);
                    c22.setClickable(false);
                    c23.setClickable(false);
                    c24.setClickable(false);
                    c25.setClickable(false);
                    c26.setClickable(false);
                    c27.setClickable(true);
                    c28.setEnabled(false);
                    c29.setEnabled(false);
                    c30.setEnabled(false);
                } else if (progressInf.equals("84")) {
                    progress.setText(progressInf + "%");
                    progressBar.setVisibility(View.INVISIBLE);
                    c1.setChecked(true);
                    c2.setChecked(true);
                    c3.setChecked(true);
                    c4.setChecked(true);
                    c5.setChecked(true);
                    c6.setChecked(true);
                    c7.setChecked(true);
                    c8.setChecked(true);
                    c9.setChecked(true);
                    c10.setChecked(true);
                    c11.setChecked(true);
                    c12.setChecked(true);
                    c13.setChecked(true);
                    c14.setChecked(true);
                    c15.setChecked(true);
                    c16.setChecked(true);
                    c17.setChecked(true);
                    c18.setChecked(true);
                    c19.setChecked(true);
                    c20.setChecked(true);
                    c21.setChecked(true);
                    c22.setChecked(true);
                    c23.setChecked(true);
                    c24.setChecked(true);
                    c25.setChecked(true);
                    c26.setChecked(true);
                    c27.setChecked(true);
                    c1.setClickable(false);
                    c2.setClickable(false);
                    c3.setClickable(false);
                    c4.setClickable(false);
                    c5.setClickable(false);
                    c6.setClickable(false);
                    c7.setClickable(false);
                    c8.setClickable(false);
                    c9.setClickable(false);
                    c10.setClickable(false);
                    c11.setClickable(false);
                    c12.setClickable(false);
                    c13.setClickable(false);
                    c14.setClickable(false);
                    c15.setClickable(false);
                    c16.setClickable(false);
                    c17.setClickable(false);
                    c18.setClickable(false);
                    c19.setClickable(false);
                    c20.setClickable(false);
                    c21.setClickable(false);
                    c22.setClickable(false);
                    c23.setClickable(false);
                    c24.setClickable(false);
                    c25.setClickable(false);
                    c26.setClickable(false);
                    c27.setClickable(false);
                    c28.setClickable(true);
                    c29.setEnabled(false);
                    c30.setEnabled(false);
                } else if (progressInf.equals("89")) {
                    progress.setText(progressInf + "%");
                    progressBar.setVisibility(View.INVISIBLE);
                    c1.setChecked(true);
                    c2.setChecked(true);
                    c3.setChecked(true);
                    c4.setChecked(true);
                    c5.setChecked(true);
                    c6.setChecked(true);
                    c7.setChecked(true);
                    c8.setChecked(true);
                    c9.setChecked(true);
                    c10.setChecked(true);
                    c11.setChecked(true);
                    c12.setChecked(true);
                    c13.setChecked(true);
                    c14.setChecked(true);
                    c15.setChecked(true);
                    c16.setChecked(true);
                    c17.setChecked(true);
                    c18.setChecked(true);
                    c19.setChecked(true);
                    c20.setChecked(true);
                    c21.setChecked(true);
                    c22.setChecked(true);
                    c23.setChecked(true);
                    c24.setChecked(true);
                    c25.setChecked(true);
                    c26.setChecked(true);
                    c27.setChecked(true);
                    c28.setChecked(true);
                    c1.setClickable(false);
                    c2.setClickable(false);
                    c3.setClickable(false);
                    c4.setClickable(false);
                    c5.setClickable(false);
                    c6.setClickable(false);
                    c7.setClickable(false);
                    c8.setClickable(false);
                    c9.setClickable(false);
                    c10.setClickable(false);
                    c11.setClickable(false);
                    c12.setClickable(false);
                    c13.setClickable(false);
                    c14.setClickable(false);
                    c15.setClickable(false);
                    c16.setClickable(false);
                    c17.setClickable(false);
                    c18.setClickable(false);
                    c19.setClickable(false);
                    c20.setClickable(false);
                    c21.setClickable(false);
                    c22.setClickable(false);
                    c23.setClickable(false);
                    c24.setClickable(false);
                    c25.setClickable(false);
                    c26.setClickable(false);
                    c27.setClickable(false);
                    c28.setClickable(false);
                    c29.setClickable(true);
                    c30.setEnabled(false);
                } else if (progressInf.equals("95")) {
                    progress.setText(progressInf + "%");
                    progressBar.setVisibility(View.INVISIBLE);
                    c1.setChecked(true);
                    c2.setChecked(true);
                    c3.setChecked(true);
                    c4.setChecked(true);
                    c5.setChecked(true);
                    c6.setChecked(true);
                    c7.setChecked(true);
                    c8.setChecked(true);
                    c9.setChecked(true);
                    c10.setChecked(true);
                    c11.setChecked(true);
                    c12.setChecked(true);
                    c13.setChecked(true);
                    c14.setChecked(true);
                    c15.setChecked(true);
                    c16.setChecked(true);
                    c17.setChecked(true);
                    c18.setChecked(true);
                    c19.setChecked(true);
                    c20.setChecked(true);
                    c21.setChecked(true);
                    c22.setChecked(true);
                    c23.setChecked(true);
                    c24.setChecked(true);
                    c25.setChecked(true);
                    c26.setChecked(true);
                    c27.setChecked(true);
                    c28.setChecked(true);
                    c29.setChecked(true);
                    c1.setClickable(false);
                    c2.setClickable(false);
                    c3.setClickable(false);
                    c4.setClickable(false);
                    c5.setClickable(false);
                    c6.setClickable(false);
                    c7.setClickable(false);
                    c8.setClickable(false);
                    c9.setClickable(false);
                    c10.setClickable(false);
                    c11.setClickable(false);
                    c12.setClickable(false);
                    c13.setClickable(false);
                    c14.setClickable(false);
                    c15.setClickable(false);
                    c16.setClickable(false);
                    c17.setClickable(false);
                    c18.setClickable(false);
                    c19.setClickable(false);
                    c20.setClickable(false);
                    c21.setClickable(false);
                    c22.setClickable(false);
                    c23.setClickable(false);
                    c24.setClickable(false);
                    c25.setClickable(false);
                    c26.setClickable(false);
                    c27.setClickable(false);
                    c28.setClickable(false);
                    c29.setClickable(false);
                    c30.setClickable(true);
                } else if (progressInf.equals("100")) {
                    progress.setText(progressInf + "%");
                    progressBar.setVisibility(View.INVISIBLE);
                    c1.setChecked(true);
                    c2.setChecked(true);
                    c3.setChecked(true);
                    c4.setChecked(true);
                    c5.setChecked(true);
                    c6.setChecked(true);
                    c7.setChecked(true);
                    c8.setChecked(true);
                    c9.setChecked(true);
                    c10.setChecked(true);
                    c11.setChecked(true);
                    c12.setChecked(true);
                    c13.setChecked(true);
                    c14.setChecked(true);
                    c15.setChecked(true);
                    c16.setChecked(true);
                    c17.setChecked(true);
                    c18.setChecked(true);
                    c19.setChecked(true);
                    c20.setChecked(true);
                    c21.setChecked(true);
                    c22.setChecked(true);
                    c23.setChecked(true);
                    c24.setChecked(true);
                    c25.setChecked(true);
                    c26.setChecked(true);
                    c27.setChecked(true);
                    c28.setChecked(true);
                    c29.setChecked(true);
                    c30.setChecked(true);
                    c1.setClickable(false);
                    c2.setClickable(false);
                    c3.setClickable(false);
                    c4.setClickable(false);
                    c5.setClickable(false);
                    c6.setClickable(false);
                    c7.setClickable(false);
                    c8.setClickable(false);
                    c9.setClickable(false);
                    c10.setClickable(false);
                    c11.setClickable(false);
                    c12.setClickable(false);
                    c13.setClickable(false);
                    c14.setClickable(false);
                    c15.setClickable(false);
                    c16.setClickable(false);
                    c17.setClickable(false);
                    c18.setClickable(false);
                    c19.setClickable(false);
                    c20.setClickable(false);
                    c21.setClickable(false);
                    c22.setClickable(false);
                    c23.setClickable(false);
                    c24.setClickable(false);
                    c25.setClickable(false);
                    c26.setClickable(false);
                    c27.setClickable(false);
                    c28.setClickable(false);
                    c29.setClickable(false);
                    c30.setClickable(false);
                }


            }

            @Override
            public void onCancelled(DatabaseError databaseError) {

            }
        });

//        if (c30.isChecked()){
//            Toast.makeText(Program.this, "Congratulations, you have completed all the programs", Toast.LENGTH_SHORT).show();
//        }


        mFirebaseUser = firebaseAuth.getCurrentUser();
        emailCurrent = mFirebaseUser.getEmail().toString();

        progress = (TextView) findViewById(R.id.progressInfo);
        emailUser = (TextView) findViewById(R.id.programUser);
        emailUser.setText(emailCurrent);


        c1 = (CheckBox) findViewById(R.id.checkbox1);
        c2 = (CheckBox) findViewById(R.id.checkbox2);
        c3 = (CheckBox) findViewById(R.id.checkbox3);
        c4 = (CheckBox) findViewById(R.id.checkbox4);
        c5 = (CheckBox) findViewById(R.id.checkbox5);
        c6 = (CheckBox) findViewById(R.id.checkbox6);
        c7 = (CheckBox) findViewById(R.id.checkbox7);
        c8 = (CheckBox) findViewById(R.id.checkbox8);
        c9 = (CheckBox) findViewById(R.id.checkbox9);
        c10 = (CheckBox) findViewById(R.id.checkbox10);
        c11 = (CheckBox) findViewById(R.id.checkbox11);
        c12 = (CheckBox) findViewById(R.id.checkbox12);
        c13 = (CheckBox) findViewById(R.id.checkbox13);
        c14 = (CheckBox) findViewById(R.id.checkbox14);
        c15 = (CheckBox) findViewById(R.id.checkbox15);
        c16 = (CheckBox) findViewById(R.id.checkbox16);
        c17 = (CheckBox) findViewById(R.id.checkbox17);
        c18 = (CheckBox) findViewById(R.id.checkbox18);
        c19 = (CheckBox) findViewById(R.id.checkbox19);
        c20 = (CheckBox) findViewById(R.id.checkbox20);
        c21 = (CheckBox) findViewById(R.id.checkbox21);
        c22 = (CheckBox) findViewById(R.id.checkbox22);
        c23 = (CheckBox) findViewById(R.id.checkbox23);
        c24 = (CheckBox) findViewById(R.id.checkbox24);
        c25 = (CheckBox) findViewById(R.id.checkbox25);
        c26 = (CheckBox) findViewById(R.id.checkbox26);
        c27 = (CheckBox) findViewById(R.id.checkbox27);
        c28 = (CheckBox) findViewById(R.id.checkbox28);
        c29 = (CheckBox) findViewById(R.id.checkbox29);
        c30 = (CheckBox) findViewById(R.id.checkbox30);
    }

    public void selectedItem(View view) {

        FirebaseUser user = firebaseAuth.getCurrentUser();

        boolean checked = ((CheckBox) view).isChecked();

        switch (view.getId()){
            case R.id.checkbox1:
                String c1 = "3";
                adapterProgres adapterProgres = new adapterProgres(c1, emailCurrent);
                databaseReference.child(user.getUid()).setValue(adapterProgres);
                startActivity(new Intent(Program.this, DetailProgram.class));
                    break;
            case R.id.checkbox2:
                String c2 = "6";
                adapterProgres a2 = new adapterProgres(c2, emailCurrent);
                databaseReference.child(user.getUid()).setValue(a2);
                startActivity(new Intent(Program.this, DetailProgram.class));
                break;
            case R.id.checkbox3:
                String c3 = "9";
                adapterProgres a3 = new adapterProgres(c3, emailCurrent);
                databaseReference.child(user.getUid()).setValue(a3);
                startActivity(new Intent(Program.this, DetailProgram.class));
                break;
            case R.id.checkbox4:
                String c4 = "12";
                adapterProgres a4 = new adapterProgres(c4, emailCurrent);
                databaseReference.child(user.getUid()).setValue(a4);
                startActivity(new Intent(Program.this, DetailProgram.class));
                break;
            case R.id.checkbox5:
                String c5 = "15";
                adapterProgres a5 = new adapterProgres(c5, emailCurrent);
                databaseReference.child(user.getUid()).setValue(a5);
                startActivity(new Intent(Program.this, DetailProgram.class));
                break;
            case R.id.checkbox6:
                String c6 = "18";
                adapterProgres a6 = new adapterProgres(c6, emailCurrent);
                databaseReference.child(user.getUid()).setValue(a6);
                startActivity(new Intent(Program.this, DetailProgram.class));
                break;
            case R.id.checkbox7:
                String c7 = "21";
                adapterProgres a7 = new adapterProgres(c7, emailCurrent);
                databaseReference.child(user.getUid()).setValue(a7);
                startActivity(new Intent(Program.this, DetailProgram.class));
                break;
            case R.id.checkbox8:
                String c8 = "24";
                adapterProgres a8 = new adapterProgres(c8, emailCurrent);
                databaseReference.child(user.getUid()).setValue(a8);
                startActivity(new Intent(Program.this, DetailProgram.class));
                break;
            case R.id.checkbox9:
                String c9 = "27";
                adapterProgres a9 = new adapterProgres(c9, emailCurrent);
                databaseReference.child(user.getUid()).setValue(a9);
                startActivity(new Intent(Program.this, DetailProgram.class));
                break;
            case R.id.checkbox10:
                String c10 = "30";
                adapterProgres a10 = new adapterProgres(c10, emailCurrent);
                databaseReference.child(user.getUid()).setValue(a10);
                startActivity(new Intent(Program.this, DetailProgram.class));
                break;
            case R.id.checkbox11:
                String c11 = "33";
                adapterProgres a11 = new adapterProgres(c11, emailCurrent);
                databaseReference.child(user.getUid()).setValue(a11);
                startActivity(new Intent(Program.this, DetailProgram.class));
                break;
            case R.id.checkbox12:
                String c12 = "36";
                adapterProgres a12 = new adapterProgres(c12, emailCurrent);
                databaseReference.child(user.getUid()).setValue(a12);
                startActivity(new Intent(Program.this, DetailProgram.class));
                break;
            case R.id.checkbox13:
                String c13 = "39";
                adapterProgres a13 = new adapterProgres(c13, emailCurrent);
                databaseReference.child(user.getUid()).setValue(a13);
                startActivity(new Intent(Program.this, DetailProgram.class));
                break;
            case R.id.checkbox14:
                String c14 = "42";
                adapterProgres a14 = new adapterProgres(c14, emailCurrent);
                databaseReference.child(user.getUid()).setValue(a14);
                startActivity(new Intent(Program.this, DetailProgram.class));
                break;
            case R.id.checkbox15:
                String c15 = "45";
                adapterProgres a15 = new adapterProgres(c15, emailCurrent);
                databaseReference.child(user.getUid()).setValue(a15);
                startActivity(new Intent(Program.this, DetailProgram.class));
                break;
            case R.id.checkbox16:
                String c16 = "48";
                adapterProgres a16 = new adapterProgres(c16, emailCurrent);
                databaseReference.child(user.getUid()).setValue(a16);
                startActivity(new Intent(Program.this, DetailProgram.class));
                break;
            case R.id.checkbox17:
                String c17 = "51";
                adapterProgres a17 = new adapterProgres(c17, emailCurrent);
                databaseReference.child(user.getUid()).setValue(a17);
                startActivity(new Intent(Program.this, DetailProgram.class));
                break;
            case R.id.checkbox18:
                String c18 = "54";
                adapterProgres a18 = new adapterProgres(c18, emailCurrent);
                databaseReference.child(user.getUid()).setValue(a18);
                startActivity(new Intent(Program.this, DetailProgram.class));
                break;
            case R.id.checkbox19:
                String c19 = "57";
                adapterProgres a19 = new adapterProgres(c19, emailCurrent);
                databaseReference.child(user.getUid()).setValue(a19);
                startActivity(new Intent(Program.this, DetailProgram.class));
                break;
            case R.id.checkbox20:
                String c20 = "60";
                adapterProgres a20 = new adapterProgres(c20, emailCurrent);
                databaseReference.child(user.getUid()).setValue(a20);
                startActivity(new Intent(Program.this, DetailProgram.class));
                break;
            case R.id.checkbox21:
                String c21 = "63";
                adapterProgres a21 = new adapterProgres(c21, emailCurrent);
                databaseReference.child(user.getUid()).setValue(a21);
                startActivity(new Intent(Program.this, DetailProgram.class));
                break;
            case R.id.checkbox22:
                String c22 = "66";
                adapterProgres a22 = new adapterProgres(c22, emailCurrent);
                databaseReference.child(user.getUid()).setValue(a22);
                startActivity(new Intent(Program.this, DetailProgram.class));
                break;
            case R.id.checkbox23:
                String c23 = "69";
                adapterProgres a23 = new adapterProgres(c23, emailCurrent);
                databaseReference.child(user.getUid()).setValue(a23);
                startActivity(new Intent(Program.this, DetailProgram.class));
                break;
            case R.id.checkbox24:
                String c24 = "72";
                adapterProgres a24 = new adapterProgres(c24, emailCurrent);
                databaseReference.child(user.getUid()).setValue(a24);
                startActivity(new Intent(Program.this, DetailProgram.class));
                break;
            case R.id.checkbox25:
                String c25 = "75";
                adapterProgres a25 = new adapterProgres(c25, emailCurrent);
                databaseReference.child(user.getUid()).setValue(a25);
                startActivity(new Intent(Program.this, DetailProgram.class));
                break;
            case R.id.checkbox26:
                String c26 = "79";
                adapterProgres a26 = new adapterProgres(c26, emailCurrent);
                databaseReference.child(user.getUid()).setValue(a26);
                startActivity(new Intent(Program.this, DetailProgram.class));
                break;
            case R.id.checkbox27:
                String c27 = "84";
                adapterProgres a27 = new adapterProgres(c27, emailCurrent);
                databaseReference.child(user.getUid()).setValue(a27);
                startActivity(new Intent(Program.this, DetailProgram.class));
                break;
            case R.id.checkbox28:
                String c28 = "89";
                adapterProgres a28 = new adapterProgres(c28, emailCurrent);
                databaseReference.child(user.getUid()).setValue(a28);
                startActivity(new Intent(Program.this, DetailProgram.class));
                break;
            case R.id.checkbox29:
                String c29 = "95";
                adapterProgres a29 = new adapterProgres(c29, emailCurrent);
                databaseReference.child(user.getUid()).setValue(a29);
                startActivity(new Intent(Program.this, DetailProgram.class));
                break;
            case R.id.checkbox30:
                String c30 = "100";
                adapterProgres a30 = new adapterProgres(c30, emailCurrent);
                databaseReference.child(user.getUid()).setValue(a30);
                startActivity(new Intent(Program.this, DetailProgram.class));
                break;



        }


    }

    @Override
    protected void onResume() {
        super.onResume();
    }

    @Override
    protected void onStart() {
        super.onStart();
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();
    }

    @Override
    protected void onStop() {
        super.onStop();
    }

    @Override
    protected void onPause() {
        super.onPause();
    }

    @Override
    protected void onRestart() {
        super.onRestart();
    }

    public void resetProgram(View view) {
        FirebaseUser user = firebaseAuth.getCurrentUser();
        String cReset = "0";
        adapterProgres aReset = new adapterProgres(cReset, emailCurrent);
        databaseReference.child(user.getUid()).setValue(aReset);
        startActivity(new Intent(Program.this, Program.class));
        finish();

    }
}
